### ISSUE TITLE
Update docs for metrics collection

### ISSUE THREAD

**Issue by doubleo2** [bitrise-steplib/bitrise-step-activate-gradle-remote-cache#21]
Metrics collection was disabled by default (see https://github.com/bitrise-steplib/bitrise-step-activate-gradle-remote-cache/commit/6fc8b9b2d3f66ab2d4912603e2c01774a33467db) but the README wasn't updated

**Comment by fabiendem** [comment]
@benbitrise, I have put a PR for this, I ran into the same issue:
https://github.com/bitrise-steplib/bitrise-step-activate-gradle-remote-cache/pull/22
